do not export as.Date.IDate anymore
Rdatatable/data.table pull request #4782
Opened 2020-10-27 11:10 UTC by jangorecki

closes #4777

2020-10-27 14:42 UTC, MichaelChirico commented
FWIW i've got a mirror of CRAN locally, statically checked if any revdeps (recursive depends/imports) were using the previous export, didn't find any.

2020-10-27 14:57 UTC, eddelbuettel commented
FWIW comes up too when letting GitHub search in the CRAN mirror:  https://github.com/search?q=org%3Acran+as.Date.IDate

2020-11-03 04:08 UTC, mattdowle requested changes

2020-11-03 04:08 UTC, mattdowle commented on NAMESPACE
> +  S3method(as.Date, IDate)
@jangorecki Why >= "3.6.0"?  Won't `as.Date(x)` break in R < 3.6.0 if the method is not exported?
Also could the comments be put back so we know there's some history on these lines pointing to #1500.

2020-11-03 04:15 UTC, mattdowle commented on NAMESPACE
> +  S3method(as.Date, IDate)
Higher up in the file the switch on 3.6.0 is about delayed registration (i.e. the `pkg::` prefix on the first argument to `S3method`) but that's not the case here with `as.Date`.

2020-11-03 04:53 UTC, mattdowle commented on NAMESPACE
> +  S3method(as.Date, IDate)
I figured the >=3.6 was copied from higher up. So I just went ahead and removed it, to merge and let's see if it passes CI. If this was wrong then we can always do a follow up PR.

2020-11-03 04:56 UTC, mattdowle commented on NAMESPACE
> +  S3method(as.Date, IDate)
When I added the suggest version for zoo, I did bit64 and bit at the same time (although nothing to do with this PR).

2020-11-03 04:58 UTC, mattdowle approved these changes

2020-11-03 05:20 UTC, merged